---
- name: Include OS Specific setup tasks
  import_tasks: setup-{{ ansible_os_family }}.yml

- name: Configure logstash
  import_task: config.yml

- name: Configure ssl
  import_task: ssl.yml
  when: logstash_configure_ssl

- name: Manage plugns
  import_tasks: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
